22S04-6 julstädning av reglementet
datasektionen/styrdokument pull request #236
Opened 2022-12-16 23:27 UTC by psoder

2022-12-22 12:55 UTC, Herkarl requested changes
Några småformateringskommentarer.

En attsats som missades under Studienämnden.

Lite inkonsekvent konsekvensnumrering inom paragrafer (subparagrafer som inte konsekvensnumrerats). 
Egentligen ska konsekvensnumreringen ske senare under motionen för KF, men kanske är fine att ha den här egentligen? Eller så blir det jobbiga merge conflict när vi gör dem andra beslutsuppföljningarna.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +- Verka för ökad integration mellan nationella och internationella studenter på EECS-skolan.
Lite felformaterad punktlista egentligen. Om alla punkter ska ha stor bokstav så ska de vara fullständiga meningar och sluta på punkt, men lite svårt att fixa åt något håll pga hur första punkten i listan är skriven.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
>  -   Sköta annat som hör bilen till.
Passa på att formatera punktlista till rätt format? Iom att andra listor ändå omformateras i PRen.

liten bokstav i början av varje punkt, och endast punkt i slutet av den sista raden.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.2 Kårfullmäktigeledamöter
Inte konsekvensnumrera ännu egentligen, ska ske i Motion för KF.

Men är väl fine så länge som det blir korrekt i slutändan och att det är rätt i de formella besluten i suppose. ¯\\\_(ツ)_/¯

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.4.1 Ändamål
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.3 Programansvarig student
konsekvensnumrerat.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.4.2 Organisation
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.4.3 Verksamhet
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.4.4 Mandatperiod
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.4 Revisorer
Konsekvensnumrerat.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +##### §5.3.4.3.3 Bokföring
Konsekvensnumrerat.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.5 Sektionshistoriker
Konsekvensnumrerad.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.6.1 Ändamål
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.6.2 Verksamhet
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.6.3 Mandatperiod
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.6 Ljud- och ljusansvarig
Konsekvensnumrerad

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +#### §5.3.7.2 Mandatperiod
Inkonsekvent konsekvensnumrerat jämfört med föräldraparagraf.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.7 Studerandeskyddsombud
Konsekvensnumrerad.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +Har till uppgift att agera som studerandeskyddsombud för sektionen. Funktionären ska såväl proaktivt som reaktivt verka för att sektionsmedlemmarnas studiemiljö är så bra som möjligt.
Det här stycket ska inte finnas här, har nog gått fel i merge.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
>  Har till uppgift att agera som studerandeskyddsombud för sektionen, med fokus på studiemiljö. Ska såväl proaktivt som reaktivt verka för att sektionsmedlemmarnas studiemiljö är så bra som möjligt.
Det här stycket ska ligga under ändamål

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +I det fall att posten är vakantsatt är Ledamot för Studiemiljö och likabehandling ställföreträdande studerandeskyddsombud
Detta stycke ska ligga under organisation.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +I det fall att posten är vakantsatt är Ledamot för Studiemiljö och likabehandling ställföreträdande studerandeskyddsombud
```suggestion
I det fall att posten är vakantsatt är Ledamot för Studiemiljö och likabehandling ställföreträdande studerandeskyddsombud.
```

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.8 D-Fest
Konsekvensnumrerad.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.9 Kommunikatör
Konsekvensnumrerad.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.10 Valberedningsledamöter
Konsekvensnumrerad.

2022-12-22 12:55 UTC, Herkarl commented on reglemente/body.md
> +### §5.3.11 Sångledare
Konsekvensnumrerad.

2022-12-23 12:08 UTC, psoder commented on reglemente/body.md
> +
Jag gillar idén av att ha en radbrytning, men det är som du säger inte så på andra ställen.

2022-12-23 12:30 UTC, psoder commented on reglemente/body.md
> +- hålla kontakten med huvudansvarig för sociala och internationella relationer på THS och de ansvariga för utbytesstudier på EECS:s kansli och institutionerna
Man kan argumentera för att det här inte är redaktionellt, men i mina ögon är det det då det inte ändrar innebörden när man delar upp punkten.

2022-12-23 12:31 UTC, psoder commented on reglemente/body.md
>  Datasladden ansvarar för att
Fixade punktlistan

2022-12-23 12:33 UTC, psoder commented on reglemente/body.md
> +### §5.3.2 Kårfullmäktigeledamöter
Jag tycker det känns mest logiskt att göra konsekvensutredningen i den här PR:en. Det är ju som du säger att så länge det blir rätt i slutändan spelar det ingen roll hur man kommer dit.

2022-12-27 13:25 UTC, abhisas commented on reglemente/body.md
> +
Jag tycker att det är en redaktionell ändring och känns rimligt.

2022-12-27 13:53 UTC, abhisas approved these changes
Bara några småkommentarer kring formattering, tycker det ser bra ut annars.

2022-12-27 13:53 UTC, abhisas commented on reglemente/body.md
> +- Masterrepresentanter för masterprogram tillhörande Datasektionen
Lägga till whitespace så vi är konsekventa.
```suggestion
-    Masterrepresentanter för masterprogram tillhörande Datasektionen
```

2022-12-27 13:53 UTC, abhisas commented on reglemente/body.md
>  -   årskursrepresentanter för de tre första årskurserna
Ändra till stor bokstav så att vi konsekvent använder stor bokstav i denna del?
```suggestion
-   Årskursrepresentanter för de tre första årskurserna
```

2022-12-27 13:53 UTC, abhisas commented on reglemente/body.md
> +-   kursnämndsrepresentanter för alla aktuella kurser
Ändra till stor bokstav så att vi konsekvent använder stor bokstav i denna del?
```suggestion
-   Kursnämndsrepresentanter för alla aktuella kurser
```

2022-12-27 13:53 UTC, abhisas commented on reglemente/body.md
>  -   övriga intresserade THS-medlemmar.
Samma som ovan
```suggestion
-   Övriga intresserade THS-medlemmar.
```

2022-12-27 13:53 UTC, abhisas commented on reglemente/body.md
> +- hålla kontakten med huvudansvarig för sociala och internationella relationer på THS och de ansvariga för utbytesstudier på EECS:s kansli och institutionerna
Håller med!

2022-12-27 14:19 UTC, Herkarl requested changes
Lite kvar att fixa under SSO

2022-12-27 14:19 UTC, Herkarl commented on reglemente/body.md
> +I det fall att posten är vakantsatt är Ledamot för Studiemiljö och likabehandling ställföreträdande studerandeskyddsombud.
Det här stycket missades under fixen, det här stycket ska ligga under organisation, och ersätta det som finns där just nu.

2022-12-27 14:28 UTC, Herkarl commented on reglemente/body.md
> +-   kursnämndsrepresentanter för alla aktuella kurser
Känner att vi får göra ett ställningstagande här, det som är grammatiskt korrekt för punktlistor på den här formen (där varje punkt inte utgör en fullständig mening), är att raderna ska börja liten bokstav (och inte ha en punkt på slutet).

PAS, DUF och SSO bör dock börja med stora bokstäver då de är titlar.

Är årksursrepresentanter, kursnämndsrepresentanter och masterrepresentanter titlar på samma sätt som de? Gjorde i min tidigare review ställningstagande att de inte var det (inser dock att jag gjorde fel i mitt förslag för tillägg med masterrepresentanter :p), men blir kanske någorlunda tveksam nu.

Övriga intresserade bör dock definitivt vara med liten bokstav.

2022-12-27 14:28 UTC, Herkarl commented on reglemente/body.md
>  -   årskursrepresentanter för de tre första årskurserna
Känner att vi får göra ett ställningstagande här, det som är grammatiskt korrekt för punktlistor på den här formen (där varje punkt inte utgör en fullständig mening), är att raderna ska börja liten bokstav (och inte ha en punkt på slutet).

PAS, DUF och SSO bör dock börja med stora bokstäver då de är titlar.

Är årksursrepresentanter, kursnämndsrepresentanter och masterrepresentanter titlar på samma sätt som de? Gjorde i min tidigare review ställningstagande att de inte var det (inser dock att jag gjorde fel i mitt förslag för tillägg med masterrepresentanter :p), men blir kanske någorlunda tveksam nu.

Övriga intresserade bör dock definitivt vara med liten bokstav.

2022-12-27 16:20 UTC, abhisas commented on reglemente/body.md
>  -   årskursrepresentanter för de tre första årskurserna
Jo, Årskursrepresentanter, Kursnämndsrepresentanter och Masterrepresentanter skull jag nog säga är titlar på samma sätt som för PAS, DUF och SNO. Håller med om att övriga intresserade bör vara med liten bokstav.

2022-12-28 00:20 UTC, psoder commented on reglemente/body.md
> +I det fall att posten är vakantsatt är Ledamot för Studiemiljö och likabehandling ställföreträdande studerandeskyddsombud.
Fixat

2022-12-28 00:22 UTC, psoder reviewed
Nu borde allting vara fixat.

2022-12-30 14:16 UTC, Adasjo approved these changes
Ser bra ut!

2022-12-30 14:17 UTC, merged