Editorial changes
datasektionen/styrdokument pull request #238
Opened 2022-12-30 23:28 UTC by psoder

closes #91 

Redaktionella ändringar, framför allt versalisering av titlar.

Fixade också konsekvent formatering av alla styrdokument. 

Markdown formatering av titlar med ========= och ----------- är katastrof.

2022-12-31 00:10 UTC, Herkarl requested changes
Har starka åsikter om titlarna högst upp i policydokumenten, se min första kommentar (bara det min `Request changes` gäller).

Tycker det är väldigt rimliga ändringar annars. Allt det med titlar och spacing vid listor kommer inte påverka något visuellt, så är ju definitivt redaktionellt.

Tycker att övrigt också är redaktionellt, men det bör väl revisorer uttrycka sig om också.

Hade några småförslag på ytterligare grejer man skulle kunna ändra, vill ha second opinion på om vissa av dem är redaktionella dock.

2022-12-31 00:10 UTC, Herkarl commented on stadgar/body.md
> +DM är beslutsmässigt om minst hälften av dess ledamöter är närvarande, och mötet är behörigt utlyst enligt §[4.2.1] Vid lika röstetal har mötesordförande utslagsröst.
Behöver lägga till en definition av länken `§[4.2.1]` i botten av dokumentet för att detta ska funka, typ:
```
[4.2.1]: #4-2-1-kallelse
```
(se repots readme för detaljer)

2022-12-31 08:46 UTC, psoder commented on alkoholpolicy/body.md
> +# Alkoholpolicy
Jag funderade också lite på det här. Jag tänkte att det var bäst att vara konsekvent inom policydokumenten, och då majoriteten hade med namnet körde jag på det. 

Sen vet jag inte vad jag tycker om att ha med namnet i `.md.` filen. Å ena sidan är det bra att ha med det så att filen blir mer fristående och det blir tydligt vad dokumentet refererar till (tbf skulle det  kunna lösas med en kommentar). Å andra sidan håller jag med om att det är fult att ha titeln två gånger.

Om man inte ska namnen som h1 tycker jag att man borde formatera om dokumenten så att alla paragrafer från h2 till h1. Detta för att vara konsekvent med stadgarna och reglementet (men håller med om att det blir lite fånigt för de mindre dokumenten).

2022-12-31 08:49 UTC, psoder commented on ekonomiskt_styrdokument/body.md
>  ### §8.3 Jubileumsfonden
Jag tycker att det vore det. Det är ett förtydligande som inte ändrar innebörden.

Det enda som talar emot är valet av namn (sektionen kanske vill döpa den till något helt annat), men det är inte ett rimligt motargument i min mening.

Men skulle säga att det är upp till @datasektionen/revisorer (och @Dpuu)

2022-12-31 08:51 UTC, psoder commented on stadgar/body.md
> +Sektionens uppgifter är att
Det känns nästan som att punktlistor förtjänar ett eget avsnitt i D-rek 101 eller verksamhetsberättelsen.

2022-12-31 08:51 UTC, psoder commented on stadgar/body.md
> +Det åligger SM att
:sunglasses:

2022-12-31 08:56 UTC, psoder commented on stadgar/body.md
> +Om inga nomineringar lämnats in vid sista nomineringsdag kan Valberedningens ordförande flytta fram nomineringsstopp samt acceptansstopp 7 dagar för den specifika posten. I händelse att det finns fär
Så jag tänkt är att i nästan alla fall (_§4.1 Sammansättning_, _§5.1 D-rektoratet_, PC-ordning, rapporter, etc.) är det Ordf, Vordf, Kassör och därför bör det vara det här också. Om det hade varit något som explicit hade med firmateckning att göra tycker jag det du säger är rimligt.

2022-12-31 10:04 UTC, Herkarl commented on alkoholpolicy/body.md
> +# Alkoholpolicy
Har funderat på det här vid tidigare tillfällen (i kontexten formatering av styrdokuments-filerna). I mina ögon så är hur det ser ut på hemsidan viktigare än hur md-filen ser ut (inom rimliga gränser). Det finns många fler fall där en person kollar på styrdokumenten på hemsidan än det finns fall som den skulle kolla i repot.

(Inte för att jag inte gillar att md-filena är snygga, har själv fixat till dem ett par gånger, ekonomiska styrdokumenten var katastrof en gång i tiden)

Funderade också på det här med att filerna skulle vara fristående. Men ser tbh inte riktigt något starkt behov av det. I de flesta fall kollar man på sakerna på hemsidan, och om man är i repot så är det väl tydligt nog från filstrukturen egentligen. (tycker det är rimligt egentligen, men att argument åt andra hållet väger mer). Fwiw så står inte titeln i reglementet eller stadgarna heller.
Håller med om att det skulle kännas mer rätt att ha alla paragrafer som h1 i md-filena. Har mindre starka åsikter om det, men tänker att tumregeln med att det är viktigare hur det ser ut på hemsidan applicerar här.

2022-12-31 10:05 UTC, Herkarl commented on ekonomiskt_styrdokument/body.md
>  ### §8.3 Jubileumsfonden
Thbs så heter den ju typ redan så iom att den benämns med det namnet i brödtexten

2022-12-31 10:07 UTC, Herkarl commented on stadgar/body.md
> +Om inga nomineringar lämnats in vid sista nomineringsdag kan Valberedningens ordförande flytta fram nomineringsstopp samt acceptansstopp 7 dagar för den specifika posten. I händelse att det finns fär
I mitt huvud så var det väldigt relaterat till firmatecknare :p iom att det är en väldigt stor del till att posterna (åtminstone kassör) väljs via urnval. Men är nog bättre att ha det enhetligt genom stadgarna hursomhaver.

2022-12-31 13:41 UTC, psoder commented on alkoholpolicy/body.md
> +# Alkoholpolicy
Ser det inte mer skevt ut på hemsidan om man har olika praxis i reglementet/stadgarna och policydokumenten? Ja de må se skevt ut för några av policiesen, men jag tror att det i helhet skulle se bättre ut.

Sen för att vara helt ärlig ser jag typ inte den titeln som står i `meta.toml`. Jag vet inte om det är för att jag har spenderat för mycket tid på sidan, om det är dålig kontrast om det ligger på ett dåligt ställe eller om det är en kombination, men jag total-ignorerar det iaf.

2022-12-31 13:42 UTC, psoder commented on ekonomiskt_styrdokument/body.md
>  ### §8.3 Jubileumsfonden
Så vi ändrar och hoppas att de inte klagar? Sounds good to me.

2023-01-01 23:07 UTC, Adasjo reviewed
Detta ser bra ut!

2023-01-01 23:41 UTC, Adasjo commented on alkoholpolicy/body.md
> +# Alkoholpolicy
Ser inga problem med att ändra h2:or till h1:or osv. Det gör det mer enhetligt på hela sidan.

2023-01-02 22:04 UTC, Herkarl commented on alkoholpolicy/body.md
> +# Alkoholpolicy
Yeah, det låter rimligt 👍 Är rimligt att ha det enhetligt

2023-01-03 00:04 UTC, psoder commented on ekonomiskt_styrdokument/body.md
> +## §8.3 50-år jubileumsfonden
Det ser rätt fult ut med "50-år jubileumsfonden", men det är mer korrekt än att skriva "50-års jubileumsfonden" då dubbelt genitiv är rätt skevt. Jag är dock ingen fena på grammatik, så jag kan ha fel.  

En annan lösning hade varit, "50-års jubileumfonden", men det blir ännu mer skevt imho. Det bästa hade kanske varit, "_50-års jubileum_-fonden"? Det lättaste kanske bara är att döpa om den till, "Stora jubileumsfonden"?

2023-01-13 12:38 UTC, Herkarl submitted a review, later dismissed
Tycker det ser bra ut :+1: 
Inte approvat fören nu för tycker det vore bra om någon @datasektionen/revisorer kollade igenom också.

2023-01-15 02:42 UTC, triggerdude33 commented
Jag kan kika på det senare idag

2023-01-16 16:23 UTC, triggerdude33 requested changes
Läste igenom allt nu. Skrev några kommentarer i reviewen på saker som borde ändras

2023-01-16 16:23 UTC, triggerdude33 commented on ekonomiskt_styrdokument/body.md
> +## §8.3 50-år jubileumsfonden
Imo fungerar 50-år jubileumsfonden

2023-01-16 16:23 UTC, triggerdude33 commented on ekonomiskt_styrdokument/body.md
> +50-år jubileumsfondens syfte är att möjliggöra ett större evenemang vid Datasektionens 50-års jubileum. Denna fond är tänkt att användas tillsammans med Jubileumsfonden (se §8.2 Jubileumsfonden) och
Mmm. Jag tycker det är ok

2023-01-16 16:23 UTC, triggerdude33 commented on informationsspridningspolicy/body.md
>  Alla kanaler där informatörer sprider information som anses intressant för sektionens medlemmar i stort, utöver de officiella, klassas som inofficiella informationskanaler. I sådana informationskanal
Näst sista meningen "Sektionen" --> "sektionen"

2023-01-16 16:23 UTC, triggerdude33 commented on informationsspridningspolicy/body.md
>  Sektionens informatörer bör vara medvetna om sin närvaro som representanter i officiella och inofficiella sammanhang - exempelvis på Datasektionens hemsida såväl som i kommentarsfält och mailinglisto
Näst sista meningen "Sektionen" --> "sektionen"

2023-01-16 16:23 UTC, triggerdude33 commented on reglemente/body.md
>  Baknämnden ska under sektionsmöten bjuda på fika till sötsugna sektionsmedlemmar. Andra delar av Sektionen ska ha möjlighet att samarbeta med Baknämnden om fikabehov finns. Vidare ska nämndens recept
Andra meningen "Sektionen" -> "sektionen"

2023-01-16 23:48 UTC, psoder commented on informationsspridningspolicy/body.md
>  Alla kanaler där informatörer sprider information som anses intressant för sektionens medlemmar i stort, utöver de officiella, klassas som inofficiella informationskanaler. I sådana informationskanal
Egentligen är det mer korrekt att skriva "sektionen" med stor bokstav då det är ett egennamn. Men jag håller med om att det är bättre att vara konsekvent och göra som på övriga ställen i styrdokumenten.

2023-01-17 13:53 UTC, triggerdude33 approved these changes
Ser bra ut

2023-01-17 14:15 UTC, merged