23S04-4 - julstädning av Reglementet
datasektionen/styrdokument pull request #270
Opened 2023-12-07 21:08 UTC by amaberg

Nu numrerar jag om ett gäng punkter som ska strykas med annan propp, men jag numrerar hellre i onödan här än att missa någon sen

2023-12-13 22:27 UTC, MalinSvenberg requested changes
En missad konsekvensnumrering, annars ser det bra ut

2023-12-13 22:27 UTC, MalinSvenberg commented on reglemente/body.md
>  #### §5.3.9.3 Mandatperiod
Borde vara 5.3.9.2 nu

2023-12-13 23:41 UTC, MalinSvenberg submitted a review, later dismissed
lgtm 👌

2023-12-14 00:37 UTC, Adasjo approved these changes

2023-12-14 00:38 UTC, merged