24S03-07 - Proposition angående Ledningsgrupp och valmöte
datasektionen/styrdokument pull request #313
Opened 2024-10-21 20:18 UTC by Adasjo

2024-11-25 10:04 UTC, frblo submitted a review, later dismissed
Lite misstag här och var som behöver återgäldas.

2024-11-30 23:18 UTC, olofbmelcherson commented on stadgar/body_sv.md
dont remove vice kassör snela

2024-11-30 23:34 UTC, olofbmelcherson requested changes
Re-add "Vice kassör"

2024-11-30 23:58 UTC, olofbmelcherson submitted a review, later dismissed
LGTM, luktar gott till maten

2024-12-01 00:04 UTC, olofbmelcherson approved these changes
satan vad gott det luktar till maten

2024-12-01 00:04 UTC, merged