24-S03-05 Proposition angående införande av talmanspresidiet
datasektionen/styrdokument pull request #323
Opened 2024-12-22 22:38 UTC by Adasjo

2024-12-22 22:38 UTC, Adasjo commented
Träder i kraft 1 januari 2025

2025-01-03 20:18 UTC, frblo requested changes

2025-01-03 20:18 UTC, frblo commented on reglemente/body_sv.md
> +#### §6.4.11.2 Organisation
Wack. JMLA är dessutom 6.4.11 ovan, vilken den inte borde vara

2025-01-03 20:19 UTC, frblo approved these changes

2025-01-03 20:19 UTC, merged